//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAHRAIN_TOURS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string company_id { get; set; }
        public string company_name { get; set; }
        public string companyLocation { get; set; }
        public string contact_person { get; set; }
        public string contact_email { get; set; }
        public string companyType { get; set; }
        public string user_id { get; set; }
    }
}
