//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAHRAIN_TOURS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string review_id { get; set; }
        public string tourists_id { get; set; }
        public string tour_id { get; set; }
        public string rating { get; set; }
        public string comment { get; set; }
    }
}
