//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAHRAIN_TOURS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourist
    {
        public string tourist_id { get; set; }
        public string full_name { get; set; }
        public string nationality { get; set; }
        public string date_of_birth { get; set; }
        public string contact_email { get; set; }
        public string tour_id { get; set; }
    }
}
