//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAHRAIN_TOURS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public string tour_id { get; set; }
        public string tour_name { get; set; }
        public string ReservationNo { get; set; }
        public string packageType { get; set; }
        public string paymentType { get; set; }
        public string decription { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string price { get; set; }
        public string company_id { get; set; }
        public string guide_id { get; set; }
    }
}
